services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.redis.endpoints=redis:6379"
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
